### ISSUE TITLE
nimbus cannot compiles with chronicles 0.7.0

### ISSUE THREAD

**Issue by jangko** [status-im/nim-chronicles#65] opened 2019-11-14 07:18 UTC
currently nimbus using chronicles 0.6.0

problem:
this two templates in `createStreamSymbol` macro

```Nim
    template outputs*(S: type `name`): auto = ({.gcsafe.}: addr `outputs`)[]
    template output* (S: type `name`): auto = ({.gcsafe.}: addr `outputs`[0])[]
```

while the `open` proc defined as:
```
proc open*(o: ptr FileOutput, path: string, mode = fmAppend): bool =
```

should it `var FileOutput` and not `ptr FileOutput`?

using chronicles 0.7.0 will produce:
```
F:\projects\nimbus-status\nimbus\nimbus.nim(61, 43) Error: type mismatch: got <FileOutput, string, FileMode>
but expected one of:
proc open(f: var File; filename: string; mode: FileMode = fmRead; bufSize: int = -1): bool
  first type mismatch at position: 1
  required type for f: var File
  but expression ' {.gcsafe.}:
  addr defaultChroniclesStreamOutputs[0]
[]' is of type: FileOutput
proc open(filename: string; mode: FileMode = fmRead; bufSize: int = -1): File
  first type mismatch at position: 1
  required type for filename: string
  but expression ' {.gcsafe.}:
  addr defaultChroniclesStreamOutputs[0]
[]' is of type: FileOutput
proc open[TMsg](c: var Channel[TMsg]; maxItems: int = 0)
  first type mismatch at position: 1
  required type for c: var Channel[open.TMsg]
  but expression ' {.gcsafe.}:
  addr defaultChroniclesStreamOutputs[0]
[]' is of type: FileOutput
proc open(f: var File; filehandle: FileHandle; mode: FileMode = fmRead): bool
  first type mismatch at position: 1
  required type for f: var File
  but expression ' {.gcsafe.}:
  addr defaultChroniclesStreamOutputs[0]
[]' is of type: FileOutput
proc open(o: ptr FileOutput; file: File): bool
  first type mismatch at position: 1
  required type for o: ptr FileOutput
  but expression ' {.gcsafe.}:
  addr defaultChroniclesStreamOutputs[0]
[]' is of type: FileOutput
proc open(o: ptr FileOutput; path: string; mode = fmAppend): bool
  first type mismatch at position: 1
  required type for o: ptr FileOutput
  but expression ' {.gcsafe.}:
  addr defaultChroniclesStreamOutputs[0]
[]' is of type: FileOutput
proc open(my: var JsonParser; input: Stream; filename: string; rawStringLiterals = false)
  first type mismatch at position: 1
  required type for my: var JsonParser
  but expression ' {.gcsafe.}:
  addr defaultChroniclesStreamOutputs[0]
[]' is of type: FileOutput
proc open(L: var BaseLexer; input: Stream; bufLen: int = 8192;
         refillChars: set[char] = NewLines)
  first type mismatch at position: 1
  required type for L: var BaseLexer
  but expression ' {.gcsafe.}:
  addr defaultChroniclesStreamOutputs[0]
[]' is of type: FileOutput

expression: open( {.gcsafe.}:
  addr defaultChroniclesStreamOutputs[0]
[], conf.debug.logFile, fmAppend)
```

**Comment by stefantalpalaru** [comment] 2019-12-02 12:45
Duplicate of https://github.com/status-im/nim-chronicles/issues/66

**Closed by stefantalpalaru** 2019-12-02 12:45 UTC
